import { Role } from '@prisma/client';
import zod from 'zod';

// export enum Role {
//   RECRUITER,
//   APPLICANT
// }

export const JobRolEnum = zod.enum([
  "FRONTEND_DEVELOPER",
  "BACKEND_DEVELOPER",
  "FULLSTACK_DEVELOPER",
  "MOBILE_DEVELOPER",
  "DEVOPS_ENGINEER",
  "QA_ENGINEER",
  "TEST_AUTOMATION_ENGINEER",
  "DATA_SCIENTIST",
  "DATA_ENGINEER",
  "MACHINE_LEARNING_ENGINEER",
  "SOFTWARE_ENGINEER",
  "SITE_RELIABILITY_ENGINEER",
  "SYSTEMS_ENGINEER",
  "SECURITY_ENGINEER",
  "CLOUD_ENGINEER",
  "PRODUCT_MANAGER",
  "TECHNICAL_PROJECT_MANAGER",
  "BUSINESS_ANALYST",
  "UI_UX_DESIGNER",
  "FRONTEND_ARCHITECT",
  "BACKEND_ARCHITECT",
  "SOFTWARE_ARCHITECT",
  "SCRUM_MASTER",
  "DATABASE_ADMINISTRATOR",
  "EMBEDDED_SOFTWARE_ENGINEER",
  "GAME_DEVELOPER",
  "HARDWARE_ENGINEER",
  "TECHNICAL_WRITER",
  "SUPPORT_ENGINEER",
  "ANALYTICS_ENGINEER",
  "FRONTEND_ENGINEER",
  "BACKEND_ENGINEER",
  "SOFTWARE_DEVELOPER",
  "MOBILE_APP_DEVELOPER",
  "NETWORK_ENGINEER",
  "DEVSECOPS_ENGINEER",
  "CLOUD_SOLUTION_ARCHITECT",
  "AI_ENGINEER",
  "NLP_ENGINEER"
])

export const DepartmentEnum = zod.enum([
  "ENGINEERING",
  "PRODUCT",
  "DESIGN",
  "MARKETING",
  "SALES",
  "HUMAN_RESOURCES",
  "FINANCE",
  "CUSTOMER_SUPPORT",
  "OPERATIONS",
  "LEGAL",
  "IT",
  "QUALITY_ASSURANCE",
  "DATA_SCIENCE",
  "RESEARCH_AND_DEVELOPMENT",
  "BUSINESS_DEVELOPMENT",
  "ADMINISTRATION",
  "SECURITY",
])

export type UserPayload = {
  userId: string;
  role: Role;
  googleId?: string;
  email?: string;
  name?: string;
  avatar?: string;
};